In [23]:
import pandas as pd
from pathlib import Path

In [24]:
PROJECT_ROOT = Path.cwd().parent

NPB_RAW = PROJECT_ROOT / "data" / "raw" / "npb"
MLB_RAW = PROJECT_ROOT / "data" / "raw" / "mlb"

In [25]:
mlb_batting = pd.read_csv(
    MLB_RAW / "Batting.csv"
)

mlb_pitching = pd.read_csv(
    MLB_RAW / "Pitching.csv"
)

mlb_people = pd.read_csv(
    MLB_RAW / "People.csv"
)

In [26]:
print(mlb_batting.shape)
print(mlb_pitching.shape)
print(mlb_people.shape)

(128598, 22)
(57630, 30)
(24270, 25)

In [27]:
print("MLB Batting columns:")
print(mlb_batting.columns.tolist())
print("MLB Pitching columns:")
print(mlb_pitching.columns.tolist())
print("MLB People columns:")
print(mlb_people.columns.tolist())

MLB Batting columns:
['playerID', 'yearID', 'stint', 'teamID', 'lgID', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP']
MLB Pitching columns:
['playerID', 'yearID', 'stint', 'teamID', 'lgID', 'W', 'L', 'G', 'GS', 'CG', 'SHO', 'SV', 'IPouts', 'H', 'ER', 'HR', 'BB', 'SO', 'BAOpp', 'ERA', 'IBB', 'WP', 'HBP', 'BK', 'BFP', 'GF', 'R', 'SH', 'SF', 'GIDP']
MLB People columns:
['ID', 'playerID', 'birthYear', 'birthMonth', 'birthDay', 'birthCity', 'birthCountry', 'birthState', 'deathYear', 'deathMonth', 'deathDay', 'deathCountry', 'deathState', 'deathCity', 'nameFirst', 'nameLast', 'nameGiven', 'weight', 'height', 'bats', 'throws', 'debut', 'bbrefID', 'finalGame', 'retroID']

In [28]:
mlb_people.head()

,ID,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,1,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,2,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101
2,3,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101
3,4,aasedo01,1954.0,9.0,8.0,Orange,USA,CA,NaN,NaN,...,Aase,Donald William,190.0,75.0,R,R,1977-07-26,aasedo01,1990-10-03,aased001
4,5,abadan01,1972.0,8.0,25.0,Palm Beach,USA,FL,NaN,NaN,...,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,abadan01,2006-04-13,abada001

In [29]:
mlb_people[
    mlb_people["birthCountry"].astype(str).str.contains(
        "Japan", case=False, na=False
    )
][[
    "playerID",
    "nameFirst",
    "nameLast",
    "birthYear",
    "birthMonth",
    "birthDay",
    "birthCountry",
    "debut"
]].head(30)

,playerID,nameFirst,nameLast,birthYear,birthMonth,birthDay,birthCountry,debut
179,akiyash01,Shogo,Akiyama,1988.0,4.0,16.0,Japan,2020-07-24
527,aokino01,Nori,Aoki,1982.0,1.0,5.0,Japan,2012-04-06
579,arihako01,Kohei,Arihara,1992.0,8.0,11.0,Japan,2021-04-03
2151,bowieji01,Jim,Bowie,1965.0,2.0,17.0,Japan,1994-08-03
3788,chitrst01,Steve,Chitren,1967.0,6.0,8.0,Japan,1990-09-05
5011,darviyu01,Yu,Darvish,1986.0,8.0,16.0,Japan,2012-04-09
6673,fenwibo01,Bobby,Fenwick,1946.0,12.0,10.0,Japan,1972-04-26
7323,fujikky01,Kyuji,Fujikawa,1980.0,7.0,21.0,Japan,2013-04-01
7324,fujinsh01,Shintaro,Fujinami,1994.0,4.0,12.0,Japan,2023-04-01
7325,fukudko01,Kosuke,Fukudome,1977.0,4.0,26.0,Japan,2008-03-31
7326,fukumka01,Kazuo,Fukumori,1976.0,8.0,4.0,Japan,2008-03-31
9169,hasegsh01,Shigetoshi,Hasegawa,1968.0,8.0,1.0,Japan,1997-04-05
9820,hiranyo01,Yoshihisa,Hirano,1984.0,3.0,8.0,Japan,2018-03-29
10123,housecr01,Craig,House,1977.0,7.0,8.0,Japan,2000-08-06
10434,igarary01,Ryota,Igarashi,1979.0,5.0,28.0,Japan,2010-04-08
10435,igawake01,Kei,Igawa,1979.0,7.0,13.0,Japan,2007-04-07
10440,iguchta01,Tadahito,Iguchi,1974.0,12.0,4.0,Japan,2005-04-04
10442,imanash01,Shota,Imanaga,1993.0,9.0,1.0,Japan,2024-04-01
10466,irabuhi01,Hideki,Irabu,1969.0,5.0,5.0,Japan,1997-07-10
10489,ishiika01,Kazuhisa,Ishii,1973.0,9.0,9.0,Japan,2002-04-06
10496,iwakuhi01,Hisashi,Iwakuma,1981.0,4.0,12.0,Japan,2012-04-20
10497,iwamuak01,Akinori,Iwamura,1979.0,2.0,9.0,Japan,2007-04-02
10777,johjike01,Kenji,Johjima,1976.0,6.0,8.0,Japan,2006-04-03
11291,kashita01,Takashi,Kashiwada,1971.0,5.0,14.0,Japan,1997-05-01
11309,kawakke01,Kenshin,Kawakami,1975.0,6.0,22.0,Japan,2009-04-11
11310,kawasmu01,Munenori,Kawasaki,1981.0,6.0,3.0,Japan,2012-04-07
11557,kidama01,Masao,Kida,1968.0,9.0,12.0,Japan,1999-04-05
11573,kikucyu01,Yusei,Kikuchi,1991.0,6.0,17.0,Japan,2019-03-21
11821,kobayma01,Masahide,Kobayashi,1974.0,5.0,24.0,Japan,2008-04-02
11862,komiysa01,Satoru,Komiyama,1965.0,9.0,15.0,Japan,2002-04-04

In [30]:
print("Batting years:", mlb_batting["yearID"].min(), "to", mlb_batting["yearID"].max())
print("Pitching years:", mlb_pitching["yearID"].min(), "to", mlb_pitching["yearID"].max())

Batting years: 1871 to 2025
Pitching years: 1871 to 2025

In [31]:
print(
    "Players in People:",
    mlb_people["playerID"].nunique()
)

print(
    "Players with batting records:",
    mlb_batting["playerID"].nunique()
)

print(
    "Players with pitching records:",
    mlb_pitching["playerID"].nunique()
)

Players in People: 24270
Players with batting records: 24011
Players with pitching records: 12134

In [32]:
mlb_batting[
    mlb_batting.duplicated(
        subset=["playerID", "yearID"],
        keep=False
    )
].head(20)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
61,abadfe01,2016,1,MIN,AL,39,1,0,0,0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
62,abadfe01,2016,2,BOS,AL,18,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
67,abadijo01,1875,1,PH3,NaN,11,45,3,10,0,...,4.0,1.0,0.0,0,3.0,NaN,NaN,NaN,NaN,0.0
68,abadijo01,1875,2,BR2,NaN,1,4,1,1,0,...,1.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,0.0
77,abbated01,1910,1,PIT,NL,3,3,0,0,0,...,0.0,0.0,NaN,0,0.0,NaN,0.0,0.0,NaN,NaN
78,abbated01,1910,2,BSN,NL,52,178,20,44,4,...,10.0,2.0,NaN,12,16.0,NaN,0.0,8.0,NaN,NaN
82,abbeybe01,1895,1,CHN,NL,1,3,0,1,0,...,0.0,0.0,NaN,0,0.0,NaN,0.0,0.0,NaN,NaN
83,abbeybe01,1895,2,BRO,NL,8,19,4,5,0,...,1.0,0.0,NaN,2,4.0,NaN,0.0,0.0,NaN,NaN
109,abbotgl01,1983,1,SEA,AL,14,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
110,abbotgl01,1983,2,DET,AL,7,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
123,abbotji01,1995,1,CHA,AL,17,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
124,abbotji01,1995,2,CAL,AL,13,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
135,abbotku01,1998,1,OAK,AL,35,123,17,33,7,...,9.0,2.0,1.0,10,34.0,0.0,1.0,1.0,1.0,3.0
136,abbotku01,1998,2,COL,NL,42,71,9,18,6,...,15.0,0.0,0.0,2,19.0,0.0,1.0,0.0,2.0,2.0
155,abbotpa01,2004,1,TBA,AL,10,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
156,abbotpa01,2004,2,PHI,NL,10,11,1,2,0,...,2.0,0.0,0.0,0,4.0,0.0,0.0,3.0,0.0,0.0
157,abelmi01,2025,1,PHI,NL,7,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
158,abelmi01,2025,2,MIN,AL,4,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
160,aberal01,1953,1,CLE,AL,6,0,0,0,0,...,0.0,0.0,0.0,2,0.0,NaN,0.0,0.0,NaN,0.0
161,aberal01,1953,2,DET,AL,17,23,2,3,0,...,2.0,0.0,0.0,1,6.0,NaN,0.0,1.0,NaN,0.0